name: hls4ml-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyter
    - tensorflow==2.1.0
    - pydot
    - graphviz
    - git+git://github.com/hls-fpga-machine-learning/hls4ml.git#egg=hls4ml[profiling]
    - git+git://github.com/google/qkeras.git#egg=qkeras
