KerasJson: KERAS_1layer.json
KerasH5:   KERAS_1layer_weights.h5
InputData: KERAS_1layer_input_features.dat
OutputPredictions: KERAS_1layer_predictions.dat
TruthLabels: KERAS_1layer_truth_labels.dat
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5
Backend: Vivado

IOType: io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<8,4>
    ReuseFactor: 1
